name: Universal Templar - Build Image

on:
  push:
    paths:
      - 'universal-templar/**'

jobs:
  build:
    uses: andronics/workflows/.github/workflows/docker-build.yml@main
    with:
      branch: "main" 
      endpoint: "andronics/universal-templar"
      root: "./universal-templar"
    secrets: inherit
  