name: Universal Templar - Build Image

on:
  push:
    paths:
      - 'universal-templar/**'

env:
  ENDPOINT: "andronics/universal-templar"
  BRANCH: "main"
  PATH: "./universal-templar"

jobs:
  build:
    uses: andronics/workflows/.github/workflows/docker-build.yml@main
    with:
      branch: $BRANCH
      endpoint: $ENDPOINT
      path: $PATH
    secrets: inherit
  